eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: service-hi
  datasource:
    url: jdbc:mysql://localhost:3306/xr
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
